---
- name: Install Docker and Django dependencies
  hosts: all
  become: yes

  tasks:
    # 1. Оновлення системи
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    # 2. Встановлення необхідних утиліт
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # 3. Додавання офіційного GPG-ключа Docker
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # 4. Додавання Docker репозиторію
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    # 5. Встановлення Docker
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    # 6. Переконатися, що Docker працює
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # 7. Додавання поточного користувача до групи Docker
    - name: Add user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # 8. Завантаження останньої версії Docker Compose
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # 9. Перевірка встановлення Docker Compose
    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_version
      changed_when: false

