name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Завантаження .env
      - name: Load .env file
        run: |
          set -a
          source .env
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

      - name: Verify DOCKER_TAG
        run: |
          echo "DOCKER_TAG=${DOCKER_TAG}"

      # Логін у Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Побудова Docker-образу
      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/django-app-dev:${DOCKER_TAG}" -f Dockerfile .

      # Завантаження Docker-образу
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-app-dev:${DOCKER_TAG}
