---
- name: Оновлення та налаштування серверів
  hosts: all
  become: yes
  vars:
    users:
      - { name: "key4", password: "1lrk5sdMb3dN2EFxW6sAt9jGv" }
    #      - { name: "keyapp", password: "GmkZ0rUFUsPRm4fn5QA6kv6WS" }
    hostnames:
      docker-core-01: "docker-core-01"
      docker-core-02: "docker-core-02"
    #      Basilisk: "basilisk"
    zabbix_server: "78.47.184.136"
    ssh_port: 22666

  tasks:
    - name: Оновлення списку пакетів та оновлення системи
      apt:
        update_cache: yes
        upgrade: yes

    - name: Встановлення часового поясу Europe/Kyiv
      timezone:
        name: Europe/Kyiv

    - name: Встановлення systemd-timesyncd (служба синхронізації часу)
      apt:
        name: systemd-timesyncd
        state: present

    - name: Увімкнення служби синхронізації часу
      systemd:
        name: systemd-timesyncd
        enabled: yes
        state: started

    - name: Налаштування time сервера (pool.ntp.org)
      lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: '^#?NTP='
        line: 'NTP=0.ua.pool.ntp.org 1.ua.pool.ntp.org'
        state: present

    - name: Перезапуск служби синхронізації часу після змін
      systemd:
        name: systemd-timesyncd
        state: restarted

    - name: Встановлення нового hostname
      hostname:
        name: "{{ hostnames[inventory_hostname] }}"

    - name: Оновлення файлу /etc/hostname
      copy:
        dest: /etc/hostname
        content: "{{ hostnames[inventory_hostname] }}\n"

    - name: Оновлення файлу /etc/hosts з новим hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^(127\.0\.1\.1\s+)'
        line: '127.0.1.1 {{ hostnames[inventory_hostname] }}'
        state: present

    - name: Створення користувачів
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"

    - name: Додавання користувачів до групи sudo
      user:
        name: "{{ item.name }}"
        groups: sudo
        append: yes
      loop: "{{ users }}"

    - name: Дозвіл користувачам виконувати sudo без пароля
      copy:
        dest: "/etc/sudoers.d/{{ item.name }}"
        content: |
          {{ item.name }} ALL=(ALL) NOPASSWD:ALL
        mode: '0440'
      loop: "{{ users }}"

    - name: Зміна порту SSH на {{ ssh_port }}
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: 'Port {{ ssh_port }}'
        state: present

    - name: Вимкнення доступу root по паролю
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin without-password'
        state: present

    - name: Перезавантаження systemd для застосування змін
      command: systemctl daemon-reload

    - name: Перезапуск SSH або ssh.socket для застосування змін
      block:
        - name: Перезапуск сервісу ssh
          service:
            name: ssh
            state: restarted
          ignore_errors: true

        - name: Перезапуск ssh.socket, якщо перезапуск ssh не вдався (для Ubuntu 24.04+)
          command: systemctl restart ssh.socket
          when: ansible_distribution_version is version('24.04', '>=')

    - name: Завантаження репозиторію Zabbix
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb"
        dest: "/tmp/zabbix-release_7.0-2+ubuntu24.04_all.deb"

    - name: Встановлення репозиторію Zabbix
      command:
        cmd: "dpkg -i /tmp/zabbix-release_7.0-2+ubuntu24.04_all.deb"
      args:
        creates: "/etc/apt/sources.list.d/zabbix.list"

    - name: Оновлення списку пакетів після додавання репозиторію Zabbix
      apt:
        update_cache: yes

    - name: Встановлення Zabbix Agent2
      apt:
        name: zabbix-agent2
        state: present

    - name: Налаштування Zabbix Agent2
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^Server=', line: "Server={{ zabbix_server }}" }
        - { regexp: '^ServerActive=', line: "ServerActive={{ zabbix_server }}" }
        - { regexp: '^Hostname=', line: "Hostname={{ hostnames[inventory_hostname] }}" }

    - name: Перезапуск та додавання в автозапуск Zabbix Agent2
      systemd:
        name: zabbix-agent2
        state: restarted
        enabled: yes

    - name: Встановлення Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Налаштування Fail2Ban (захист SSH)
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port = {{ ssh_port }}
          filter = sshd
          action = iptables-multiport[name=SSH, port={{ ssh_port }}, protocol=tcp]
          logpath = /var/log/auth.log
          maxretry = 5
        mode: '0644'

    - name: Перезапуск та включення Fail2Ban
      systemd:
        name: fail2ban
        state: restarted
        enabled: yes

    - name: Встановлення iptables-persistent
      apt:
        name: iptables-persistent
        state: present
        install_recommends: yes
