version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    volumes:
      - .:/src

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      
