apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw21-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw24-app
  template:
    metadata:
      labels:
        app: hw24-app
    spec:
      containers:
        - name: hw24-containers
          image: a3888s/hw24:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: hw24-service
spec:
  selector:
    app: hw24-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
