- name: Set timezone to Europe/Kyiv
  timezone:
    name: Europe/Kyiv

- name: Install systemd-timesyncd
  apt:
    name: systemd-timesyncd
    state: present

- name: Enable timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: Configure NTP servers
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#?NTP='
    line: 'NTP=0.ua.pool.ntp.org 1.ua.pool.ntp.org'

- name: Restart timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted